/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author bharatsingh
 */
import Model.User;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.regex.*;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.*;
public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private JPanel BottomPanel;
    public FormPanel(JPanel inputPanel) {
        initComponents();
        this.BottomPanel=inputPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Swing_Assignment = new javax.swing.JPanel();
        Title_Label = new javax.swing.JLabel();
        First_Name_Label = new javax.swing.JLabel();
        First_Name_Input = new javax.swing.JTextField();
        Submit_Button = new javax.swing.JButton();
        Age_Input = new javax.swing.JTextField();
        Age_Label = new javax.swing.JLabel();
        First_Name_Validation = new javax.swing.JLabel();
        Age_Validation = new javax.swing.JLabel();

        Swing_Assignment.setBackground(new java.awt.Color(204, 255, 204));

        Title_Label.setFont(new java.awt.Font("Kohinoor Bangla", 3, 36)); // NOI18N
        Title_Label.setForeground(new java.awt.Color(51, 51, 255));
        Title_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_Label.setText("Patient Registration Form");

        First_Name_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        First_Name_Label.setText("Name");

        First_Name_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_Name_InputActionPerformed(evt);
            }
        });
        First_Name_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                First_Name_InputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                First_Name_InputKeyTyped(evt);
            }
        });

        Submit_Button.setText("Submit");
        Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_ButtonActionPerformed(evt);
            }
        });

        Age_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_InputActionPerformed(evt);
            }
        });
        Age_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Age_InputKeyReleased(evt);
            }
        });

        Age_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Age_Label.setText("Age");

        First_Name_Validation.setBackground(new java.awt.Color(255, 255, 0));
        First_Name_Validation.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        First_Name_Validation.setForeground(new java.awt.Color(255, 0, 0));

        Age_Validation.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        Age_Validation.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout Swing_AssignmentLayout = new javax.swing.GroupLayout(Swing_Assignment);
        Swing_Assignment.setLayout(Swing_AssignmentLayout);
        Swing_AssignmentLayout.setHorizontalGroup(
            Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                        .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Submit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(First_Name_Label)
                                    .addComponent(Age_Label))
                                .addGap(75, 75, 75)
                                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(First_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Age_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(First_Name_Validation)
                                    .addComponent(Age_Validation))))
                        .addGap(33, 33, 33)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        Swing_AssignmentLayout.setVerticalGroup(
            Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_Name_Label)
                    .addComponent(First_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(First_Name_Validation))
                .addGap(33, 33, 33)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Age_Label)
                    .addComponent(Age_Validation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(Submit_Button)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Swing_Assignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Swing_Assignment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        
   
        if(First_Name_Validation==null && Age_Validation==null)
        {
            JOptionPane.showMessageDialog(this, "Registration Successful", "Success", HEIGHT);
        }
        else{JOptionPane.showMessageDialog(this, "Enter valid details", "Error", HEIGHT);}
    }                                             

    private void First_Name_InputKeyTyped(java.awt.event.KeyEvent evt) {                                          
        // TODO add your handling code here:
        //String valid_str= "^[a-zA-z]$";
    }                                         

    private void First_Name_InputKeyReleased(java.awt.event.KeyEvent evt) {                                             
        // TODO add your handling code here:
        Pattern pattern=Pattern.compile("^[a-zA-Z+ ]{1,30}$");
        Matcher matcher=pattern.matcher(First_Name_Input.getText());
        boolean Validation =matcher.find();
        if (!Validation){First_Name_Validation.setText("First name Invalid");}
        else{First_Name_Validation.setText(null);}
    }                                            

    private void First_Name_InputActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void Age_InputKeyReleased(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        Pattern pattern=Pattern.compile("^[0-9]{1,3}$");
        Matcher matcher=pattern.matcher((Age_Input.getText()));
        boolean Validation =matcher.find();
        if (!Validation){Age_Validation.setText("Invalid age");}
        else{Age_Validation.setText(null);}
    }                                     

    private void Age_InputActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         


    // Variables declaration - do not modify                     
    private javax.swing.JTextField Age_Input;
    private javax.swing.JLabel Age_Label;
    private javax.swing.JLabel Age_Validation;
    private javax.swing.JTextField First_Name_Input;
    private javax.swing.JLabel First_Name_Label;
    private javax.swing.JLabel First_Name_Validation;
    private javax.swing.JButton Submit_Button;
    private javax.swing.JPanel Swing_Assignment;
    private javax.swing.JLabel Title_Label;
    // End of variables declaration                   
}
